[package]
name = "release_crates"
version = "0.1.0"
edition = "2021"
desciption = "Test of my first crate release"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
